In [1]:
import numpy as np

In [3]:
data = np.array([[1,2,3],[4,5,6],[7,8,9],[7,5,9]])

In [5]:
mean = data.mean(axis=0)
std = data.std(axis=0)

In [6]:
normalized_data = (data-mean)/std
print(normalized_data)

[[-1.50755672 -1.41421356 -1.50755672]
 [-0.30151134  0.         -0.30151134]
 [ 0.90453403  1.41421356  0.90453403]
 [ 0.90453403  0.          0.90453403]]
