In [1]:
import numpy as np

In [14]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[1,5,9]])

In [15]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 5, 9]])

In [6]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.full((4,6),7)

array([[7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7]])

In [9]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.arange(1,100,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [13]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [20]:
print("The shape : ",arr.shape)

The shape :  (4, 3)


In [21]:
print("The size: ", arr.size)

The size:  12


In [22]:
print("Dimension: ",arr.ndim)

Dimension:  2


In [23]:
print("Data Type: ",arr.dtype)

Data Type:  int64


In [26]:
reshaped = arr.reshape((3,4))

In [27]:
reshaped

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 5, 9]])

In [28]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 5, 9]])