In [1]:
import numpy as np

In [16]:
data = np.array([1,5,9,7,3,3])

In [17]:
data

array([1, 5, 9, 7, 3, 3])

In [18]:
np.mean(data)

np.float64(4.666666666666667)

In [19]:
np.std(data)

np.float64(2.6874192494328497)

In [20]:
print("variance: ", np.var(data))

variance:  7.222222222222221


In [21]:
print("Min: ", np.min(data))

Min:  1


In [22]:
print("Max: ", np.max(data))

Max:  9


In [23]:
print("Product: ", np.prod(data))

Product:  2835


In [24]:
print("Median: ", np.median(data))

Median:  4.0


In [25]:
print("Percentile: ", np.percentile(data,70))

Percentile:  6.0


In [26]:
print("Index of the minimum: ", np.argmin(data))

Index of the minimum:  0


In [27]:
print("Index of the maxmum: ", np.argmax(data))

Index of the maxmum:  2


In [30]:
data1 = np.array([7,8,9,5,3])
data2 = np.array([4,5,6,7,1])
print("Correlation coefficient: ", np.corrcoef(data1,data2))

Correlation coefficient:  [[1.         0.57716242]
 [0.57716242 1.        ]]


In [32]:
print("Unique data list: ", np.unique(data))

Unique data list:  [1 3 5 7 9]


In [33]:
print("n-th difference of the array: ", np.diff(data))

n-th difference of the array:  [ 4  4 -2 -4  0]


In [34]:
print("Cumulative Sum: ", np.cumsum(data))

Cumulative Sum:  [ 1  6 15 22 25 28]


In [35]:
np.linspace(0,100,15)

array([  0.        ,   7.14285714,  14.28571429,  21.42857143,
        28.57142857,  35.71428571,  42.85714286,  50.        ,
        57.14285714,  64.28571429,  71.42857143,  78.57142857,
        85.71428571,  92.85714286, 100.        ])

In [36]:
np.log(data)

array([0.        , 1.60943791, 2.19722458, 1.94591015, 1.09861229,
       1.09861229])

In [37]:
np.exp(data)

array([2.71828183e+00, 1.48413159e+02, 8.10308393e+03, 1.09663316e+03,
       2.00855369e+01, 2.00855369e+01])