In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[1,5,9]])

In [3]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 5, 9]])

In [4]:
np.sum(arr, axis=0)

array([13, 20, 27])

In [5]:
np.sum(arr, axis=1)

array([ 6, 15, 24, 15])

In [6]:
arr[0][1]

np.int64(2)

In [8]:
arr[0:4, 1:3]

array([[2, 3],
       [5, 6],
       [8, 9],
       [5, 9]])

In [11]:
arr3d = np.array([
    [ [1,2,3],
      [4,5,6] ],
    [ [ 7,8,9],
      [7,5,3]]
    ])

In [12]:
arr3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [7, 5, 3]]])

In [14]:
print(arr3d [ :,  0 , : ] )

[[1 2 3]
 [7 8 9]]
