In [2]:
import numpy as np

In [3]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[1,5,9]])

In [4]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 5, 9]])

In [5]:
flat = arr.flatten()

In [6]:
flat

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 5, 9])

In [7]:
flat[0]

np.int64(1)

In [8]:
flat[3:6]

array([4, 5, 6])

In [9]:
flat[:5]

array([1, 2, 3, 4, 5])

In [10]:
flat[3:]

array([4, 5, 6, 7, 8, 9, 1, 5, 9])

In [11]:
flat[::2]

array([1, 3, 5, 7, 9, 5])

In [14]:
arr[arr>3]

array([4, 5, 6, 7, 8, 9, 5, 9])